### ISSUE TITLE
Add initial Alpine-based docker image

### ISSUE THREAD

**Issue by michaeltlombardi** [lingua-pupuli/images#1]
To move forward on jpogran/puppet-vscode#212 we need a language server docker container. We should be able to build off of the [puppet-in-docker](https://github.com/puppetlabs/puppet-in-docker) project for base images to build on for everything except for Windows, which we'll probably have to build ourselves.

The first target should be Alpine, as it's the slimmest of the target images.

**Comment by jpogran** [comment]
done
