### ISSUE TITLE
RFC: Imaging Matrix

### ISSUE THREAD

**Issue by michaeltlombardi** [lingua-pupuli/images#5]
We need to clarify how we're going to name and tag these (a few options below):

- `linguapupuli/puppet-language-server`
  - `:platform-platform_version-type-type_version-server-server_version` - full set of info you might want about an image, where platform is windows or alpine, type is agent or pdk.
  - `:platform-type-type_version-server-server_version` - As above, assume latest for platform.
  - `:platform-type-type_version` - As above, assume latest for language server.
  - `:platform-type` - As above, assume latest for all.
  - `:platform` - As above, but with 'default' type (agent for now, pdk in future?)
  - `:latest` - As above, but default OS (probably alpine).
- `linguapupuli/puppet-language-server-platform` - one for each platform
  - `:platform_version-type-type_version-server-server_version` - full set of info you might want
  - `:type-type_version-server-server_version` - As above, assume latest platform
  - `:type-type_version` - As above, assume latest language server
  - `:type` - as above, assume latest version of agent or pdk
  - `:latest` - as above, assume latest version of 'default' type
- `linguapupuli/puppet-language-server-type` - one for agent, one for pdk
  - `:type_version-platform-platform_version-server-server_version` - full set of info you might want
  - `:type_version-platform-server-server_version` - assume latest platform
  - `:type_version-platform` - assume latest server version
  - `:platform` - assume latest agent or pdk install
  - `:latest` - assume latest install for default platform
- `linguapupuli/puppet-language-server-type-platform` or `linguapupuli/puppet-language-servver-platform-type`
  - `:type_version-server-server_version` - assume latest for platform
  - `:type_version` - assume latest server version
  - `:latest` - assume latest for this platform and install type

The first or the last are probably the easiest to grok, for me - I advise always defaulting to latest available platform, we _may_ want to eventually support a more full matrix of pdk/agent install versions, but we probably also always want to add latest language server?

ie, assuming the first option (most explicit):

- `:agent-v5.5.1-server-0.12.0` on default platform (alpine?)
- `:agent-v5.5.1-server-0.13.0` on default platform (alpine?)
- `:agent-v5.5.1-server-0.14.0` on default platform (alpine?)
- `:agent-v5.5.1` - latest version of server at build time on default platform (alpine?)
- `:agent-v6.0.2-server-0.13.0` on default platform (alpine?)
- `:agent-v6.0.2-server-0.14.0` on default platform (alpine?)
- `:agent-v6.0.2` - latest version of server at build time on default platform (alpine?)
- `:agent` - latest version of agent and server at build time  on default platform (alpine?)
- `:alpine-agent-v5.5.1-server-0.12.0`
- `:alpine-agent-v5.5.1-server-0.13.0`
- `:alpine-agent-v5.5.1-server-0.14.0`
- `:alpine-agent-v5.5.1` - latest version of server at build time
- `:alpine-agent-v6.0.2-server-0.13.0`
- `:alpine-agent-v6.0.2-server-0.14.0`
- `:alpine-agent-v6.0.2` - latest version of server at build time
- `:alpine-agent` - latest version of agent and server at build time
- `:alpine-pdk-v1.7.1-server-0.12.0`
- `:alpine-pdk-v1.7.1-server-0.13.0`
- `:alpine-pdk-v1.7.1-server-0.14.0`
- `:alpine-pdk-v1.7.1` - latest version of server at build time
- `:alpine-pdk-v1.7.2-server-0.13.0`
- `:alpine-pdk-v1.7.2-server-0.14.0`
- `:alpine-pdk-v1.7.2` - latest version of server at build time
- `:alpine-pdk` - latest version of pdk and server at build time
- `:alpine` - latest version of default install type (agent?) and server at build time.
- `:latest` - latest version of default install type (agent?) and server at build time on default platform (alpine?)
- `:pdk-v1.7.1-server-0.12.0` on default platform (alpine?)
- `:pdk-v1.7.1-server-0.13.0` on default platform (alpine?)
- `:pdk-v1.7.1-server-0.14.0` on default platform (alpine?)
- `:pdk-v1.7.1` - latest version of server at build time on default platform (alpine?)
- `:pdk-v1.7.2-server-0.13.0` on default platform (alpine?)
- `:pdk-v1.7.2-server-0.14.0` on default platform (alpine?)
- `:pdk-v1.7.2` - latest version of server at build time on default platform (alpine?)
- `:pdk` - latest version of pdk and server at build time on default platform (alpine?)
- `:windows-agent-v5.5.1-server-0.12.0`
- `:windows-agent-v5.5.1-server-0.13.0`
- `:windows-agent-v5.5.1-server-0.14.0`
- `:windows-agent-v5.5.1` - latest version of server at build time
- `:windows-agent-v6.0.2-server-0.13.0`
- `:windows-agent-v6.0.2-server-0.14.0`
- `:windows-agent-v6.0.2` - latest version of server at build time
- `:windows-agent` - latest version of agent and server at build time
- `:windows-pdk-v1.7.1-server-0.12.0`
- `:windows-pdk-v1.7.1-server-0.13.0`
- `:windows-pdk-v1.7.1-server-0.14.0`
- `:windows-pdk-v1.7.1` - latest version of server at build time
- `:windows-pdk-v1.7.2-server-0.13.0`
- `:windows-pdk-v1.7.2-server-0.14.0`
- `:windows-pdk-v1.7.2` - latest version of server at build time
- `:windows-pdk` - latest version of pdk and server at build time
- `:windows` - latest version of default install type (agent?) and server at build time.

But you'd only build four images each time (alpine agent, alpine pdk, windows agent, windows pdk), unless you wanted to rebuild old versions with new versions of the language server.

Assuming the latest version of the agent is `6.0.2` and the latest version of the language server is `0.14.0`:

- Build the agent image for alpine, tag with all of these:
  - `:agent-v6.0.2-server-0.14.0`
  - `:agent-v6.0.2`
  - `:agent`
  - `:alpine-agent-v6.0.2-server-0.14.0`
  - `:alpine-agent-v6.0.2`
  - `:alpine-agent`
  - `:alpine`
  - `:latest`
- Build the pdk image for alpine, tag with all of these:
  - `:alpine-pdk-v1.7.2-server-0.14.0`
  - `:alpine-pdk`
  - `:pdk-v1.7.2-server-0.14.0` on default platform (alpine?)
  - `:pdk-v1.7.2`
  - `:pdk`
- Build the agent image for windows, tag with all of these:
  - `:windows-agent-v6.0.2-server-0.14.0`
  - `:windows-agent-v6.0.2`
  - `:windows-agent`
  - `:windows`
- Build the pdk image for windows, tag with all of these:
  - `:windows-pdk-v1.7.2-server-0.14.0`
  - `:windows-pdk-v1.7.2`
  - `:windows-pdk`

**Comment by jpogran** [comment]
I've spent some time experimenting with building docker images with published packages for puppet-agent and pdk on docker windows containers, with the end goal being a docker image using pdk as the source for the gems the language server needs.

A longer write-up of that is still in progress, but the results are that the only method that works at the moment for pdk is to install it as a gem. The windows pdk package does not work well, or at all in windows containers right now. A working windows container is obtained by installing ruby and git, then installing the puppet and dependent gems after.

In retrospect, since these containers are purpose built for the language server it makes sense that we don't strictly 'need' the pdk package at this juncture. PDK is useful for a development environment that works in any and all cases, but we have a simpler and more constrained case.

I suggest we reduce our matrix to an alpine and windowservercore container list, with the alpine using the latest puppetlabs/puppet-agent-alpine and the windowservercore being custom built by us until puppet publishes their own builds.

**Comment by michaeltlombardi** [comment]
I'm perfectly happy to maintain a smaller matrix (and we can always add new tags later anyway).

The following matrices pretends the latest two version of the language server are `0.13.0` and `0.14.0` and that the latest two versions of Puppet Agent are `6.0.2` and `6.0.3`.

## One Image, Many Tags

- `lingua-pupuli/puppet-language-server`

| Platform | Language Server Version | Puppet Agent Version | Tags |
|:--------:|:-----------------------:|:--------------------:|:-----|
| Alpine   | 0.13.0                  | 6.0.2                | `:alpine-agent-6.0.2-server-0.13.0`, `:agent-6.0.2-server-0.13.0`
| Alpine   | 0.13.0                  | 6.0.3                | `:alpine-agent-6.0.3-server-0.13.0`, `:alpine-server-0.13.0`, `:agent-6.0.3-server-0.13.0`, `:server-0.13.0`
| Alpine   | 0.14.0                  | 6.0.2                | `:alpine-agent-6.0.2-server-0.14.0`, `:alpine-agent-6.0.2`, `:agent-6.0.2-server-0.14.0`, `:agent-6.0.2`
| Alpine   | 0.14.0                  | 6.0.3                | `:alpine-agent-6.0.3-server-0.14.0`, `:alpine-agent-6.0.3`, `:alpine-server-0.14.0`, `:alpine-latest`, `:agent-6.0.3-server-0.14.0`, `:agent-6.0.3`, `:server-0.14.0`, `:latest`
| Windows  | 0.13.0                  | 6.0.2                | `:windows-agent-6.0.2-server-0.13.0`
| Windows  | 0.13.0                  | 6.0.3                | `:windows-agent-6.0.3-server-0.13.0`, `:windows-server-0.13.0`
| Windows  | 0.14.0                  | 6.0.2                | `:windows-agent-6.0.2-server-0.14.0`, `:windows-agent-6.0.2`
| Windows  | 0.14.0                  | 6.0.3                | `:windows-agent-6.0.3-server-0.14.0`, `:windows-agent-6.0.3`, `:windows-server-0.14.0`, `:windows`

## Two Images

- `lingua-pupuli/puppet-language-server-alpine`
- `lingua-pupuli/puppet-language-server-windows`

| Platform | Language Server Version | Puppet Agent Version | Tags |
|:--------:|:-----------------------:|:--------------------:|:-----|
| Alpine   | 0.13.0                  | 6.0.2                | `:agent-6.0.2-server-0.13.0`
| Alpine   | 0.13.0                  | 6.0.3                | `:agent-6.0.3-server-0.13.0`, `:server-0.13.0`
| Alpine   | 0.14.0                  | 6.0.2                | `:agent-6.0.2-server-0.14.0`, `:agent-6.0.2`
| Alpine   | 0.14.0                  | 6.0.3                | `:agent-6.0.3-server-0.14.0`, `:agent-6.0.3`, `:server-0.14.0`, `:latest`
| Windows  | 0.13.0                  | 6.0.2                | `:agent-6.0.2-server-0.13.0`
| Windows  | 0.13.0                  | 6.0.3                | `:agent-6.0.3-server-0.13.0`, `:server-0.13.0`
| Windows  | 0.14.0                  | 6.0.2                | `:agent-6.0.2-server-0.14.0`, `:agent-6.0.2`
| Windows  | 0.14.0                  | 6.0.3                | `:agent-6.0.3-server-0.14.0`, `:agent-6.0.3`, `:server-0.14.0`, `:latest`

**Comment by jpogran** [comment]
With the release of Microsoft Remote Container Extension and the official pdk docker images, this issue is no longer needed
